name: easylense_prototype
description: "EasyLens — Assistive navigation for visually impaired users."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_tts: ^4.2.0
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.5
  image_picker: ^1.1.2
  minio_new: ^1.0.2
  path: ^1.9.0
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  battery_plus: ^6.0.2
  shared_preferences: ^2.3.2
  google_generative_ai: ^0.4.6
  speech_to_text: ^6.6.1
  tflite_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo/easylens_logo.png
    - assets/images/logo/secondary_logo.png
    - assets/images/introduction_icons/
    - assets/icons/auth_icon/service_icons/
    - assets/icons/auth_icon/forgot-password-icon/
    - assets/icons/auth_icon/signup_icon/
    - assets/icons/navbar-icon/
    - assets/icons/hamburger-menu-icons/
    - assets/icons/hazards-icons/
    - assets/icons/object-icon/
    - assets/animation/
    - assets/app_icon_logo.png
    - assets/models/ssd_mobilenet_v2_quantized.tflite
    - assets/models/labels.txt

  fonts:
    - family: HeaderFont
      fonts:
        - asset: assets/fonts/header_font/AtkinsonHyperlegible-Regular.ttf
        - asset: assets/fonts/header_font/AtkinsonHyperlegible-Bold.ttf
          weight: 700
    - family: DescriptionFont
      fonts:
        - asset: assets/fonts/description_font/AtkinsonHyperlegibleMono-VariableFont_wght.ttf

dependency_overrides:
  http: ^1.2.0
